# Connects to the Docker PostgreSQL container
spring.datasource.url=jdbc:postgresql://hyperlocal_postgres:5432/hyperlocal_db
spring.datasource.username=postgres
spring.datasource.password=postgrespassword

# Prevents Spring from overwriting the PostGIS tables we already made
spring.jpa.hibernate.ddl-auto=none

# Tells Spring to use the spatial PostGIS dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080